Repository CodeQuizz/CodeQuizz_main, pull requests merged in 2024-12, with the labels that each got.

#7 sungmin readme
  README.md
Labels: documentation

#11 [#10]Chore: 초기 설정
  .github/ISSUE_TEMPLATE/issue_feature_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .gitignore
  Home.py
  README.md
  pages/Login.py
  requirements.txt
Labels: low

#17 [#15]feat: 메인퀴즈페이지 구현
  main_quiz.py
  quiz_questions.json
Labels: enhancement

#21 [#19]fix: 메인페이지 난이도 설정 구현
  main_quiz.py
Labels: enhancement

#22 [#19]fix : 파일 이름 수정
  data/quiz_questions.json
  pages/Main.py
Labels: bug

#24 [#18] Feat: 로그인페이지 기능 구현
  data/users.json
  pages/Login.py
Labels: low

#23 [#20] fix: 결과 페이지 파라미터 오류 수정
  pages/Results.py
Labels: bug

#27 [#25] feature: 메인페이지에서 결과페이지로 이동 구현
  pages/Main.py
Labels: enhancement

#30 [#29] fix: 메인페이지의 점수 결과페이지로 전달 수정
  pages/Main.py
Labels: bug

#32 [#31]Refactor: 파일 구조 수정 및 기능 개선
  .github/pull_request_template.md
  Home.py
  pages/Login.py
  pages/Main.py
  pages/Results.py
Labels: low

#34 [#26]Chore : result 기능 개선 후 메인 페이지 병합
  pages/Main.py
  pages/Results.py
Labels: bug

#37 [#36]Feat : 결과 페이지 오답 분석 기능 추가
  pages/Main.py
  pages/Results.py
Labels: enhancement

#38 [#35]설명서 기능 추가
  Home.py
Labels: enhancement

#40 [#39] style: 메인페이지 ui 개선
  pages/Main.py
Labels: enhancement

#42 [#41] Fix: Main.py의 로그아웃 기능 수정
  pages/Main.py
Labels: bug

#46 [#45]Feat: 로그아웃 기능 수정
  pages/Main.py
Labels: bug

#50 [#47]Docs: R&R 문서 추가 및 수정
  report/RNR.md
Labels: documentation

#52 Docs/#49/WF
  report/요구사항명세서.md
  report/화면설계서.md
Labels: documentation

#53 [#51] Docs: wbs 문서 작성
  report/RNR.md
  report/WBS.md
Labels: documentation

#54 [#51] Docs: wbs 문서 작성(수정본)
  report/WBS.md
  report/화면설계서.pdf
Labels: documentation

#55 [#48]Docs: 요구 사항 명세서 작성
  report/요구사항명세서.md
Labels: documentation

#56 merge: Main 브런치에 develop 브런치 병합
  .github/ISSUE_TEMPLATE/issue_feature_template.md
  .github/pull_request_template.md
  .gitignore
  Home.py
  README.md
  assets/How To Use.png
  assets/coding.png
  data/quiz_questions.json
  data/users.json
  pages/Login.py
  pages/Main.py
  pages/Results.py
  report/RNR.md
  report/WBS.md
  report/image-1.png
  report/image-2.png
  report/image-3.png
  report/image-4.png
  report/image.png
  report/요구사항명세서.md
  report/화면설계서.md
  report/화면설계서.pdf
  requirements.txt
Labels: low

#58 [#57]Feat: 인터렉티브한 코드 문제 구현
  pages/Interactive.py
  pages/Main.py
  pages/Results.py
Labels: low

#61 [#60]feat: login 유저 정보 개선
  pages/Login.py
  pages/Main.py
  pages/Results.py
Labels: enhancement

#65 [#64]feat: 출석 체크 기능 추가
  Home.py
  data/attendance.json
  report/요구사항명세서.pdf
Labels: enhancement

#67 [#66]feat: 결과페이지에 교재 추천 기능 구현
  README.pdf
  pages/Results.py
Labels: enhancement

#69 [#68]fix: 결과페이지의 시각화 오류 수정
  pages/Results.py
Labels: bug

#71 [#70]docs: 요구사항명세서, 화면설계서, RNR.md 업데이트
  report/RNR.md
  report/image-6.png
  report/image-7.png
  report/요구사항명세서.md
  report/화면설계서.md
Labels: documentation
